[package]
name = "bitboard"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2.92"

[lib]
path="src/rust/lib.rs"
crate-type=["cdylib"]

[profile.release]
lto = true